name: Github Activity in Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "refactor: ♻️ Update README with the recent activity"
          EMPTY_COMMIT_MSG: "chore: 🚧 Empty commit to keep workflow active after 60 days of no activity"
          MAX_LINES: 5
          COMMIT_NAME: "GitHub Activity Readme Bot"
          COMMIT_EMAIL: "github-activity-readme-bot@rubn.dev"
